const exactRevealTerms = new Map([
  ["802.1q trunk", "IEEE 802.1Q trunk"],
  ["802.1x network access control", "IEEE 802.1X network access control"],
  ["aaaa record", "IPv6 address record (AAAA)"],
  ["acl", "Access control list"],
  ["apipa", "Automatic Private IP Addressing"],
  ["arp", "Address Resolution Protocol (ARP) command"],
  ["bnc", "Bayonet Neill-Concelman connector"],
  ["bssid", "Basic service set identifier"],
  ["cidr", "Classless Inter-Domain Routing"],
  ["crc error", "Cyclic redundancy check (CRC) error"],
  ["ddos", "Distributed denial of service"],
  ["dhcp", "Dynamic Host Configuration Protocol"],
  ["dig", "Domain Information Groper (dig)"],
  ["dns", "Domain Name System"],
  ["dos", "Denial of service"],
  ["duplicate ip", "Duplicate Internet Protocol address"],
  ["electromagnetic interference (emi)", "Electromagnetic interference"],
  ["emi", "Electromagnetic interference"],
  ["eol", "End of life"],
  ["eos", "End of support"],
  ["ftp", "File Transfer Protocol"],
  ["http", "Hypertext Transfer Protocol"],
  ["https", "Hypertext Transfer Protocol Secure"],
  ["idf", "Intermediate distribution frame"],
  ["ifconfig", "Interface configuration command"],
  ["intrusion detection system (ids)", "Intrusion detection system"],
  ["intrusion prevention system (ips)", "Intrusion prevention system"],
  ["ip address", "Internet Protocol address"],
  ["ip address (linux command)", "Internet Protocol address (Linux command)"],
  ["ipam", "IP address management"],
  ["ipconfig", "IP configuration command"],
  ["ipsec", "Internet Protocol Security"],
  ["mac address", "Media access control address"],
  ["mac address table", "Media access control address table"],
  ["mac flooding", "Media access control flooding"],
  ["mdf", "Main distribution frame"],
  ["mfa", "Multi-factor authentication"],
  ["mtbf", "Mean time between failures"],
  ["mttr", "Mean time to repair"],
  ["nac", "Network access control"],
  ["nas", "Network-attached storage"],
  ["nat", "Network address translation"],
  ["ndp", "Neighbor Discovery Protocol"],
  ["netstat", "Network statistics command"],
  ["nmap", "Network Mapper"],
  ["nslookup", "Name server lookup"],
  ["ntp", "Network Time Protocol"],
  ["optical time-domain reflectometer (otdr)", "Optical time-domain reflectometer"],
  ["otdr", "Optical time-domain reflectometer"],
  ["pat", "Port address translation"],
  ["pdu", "Power distribution unit"],
  ["poe budget", "Power over Ethernet budget"],
  ["poe budget exhaustion", "Power over Ethernet budget exhaustion"],
  ["qsfp", "Quad small form-factor pluggable"],
  ["quality of service (qos)", "Quality of Service"],
  ["radius", "Remote Authentication Dial-In User Service"],
  ["rbac", "Role-based access control"],
  ["rdp", "Remote Desktop Protocol"],
  ["rpo", "Recovery point objective"],
  ["rogue ap", "Rogue access point"],
  ["rssi", "Received signal strength indicator"],
  ["rto", "Recovery time objective"],
  ["san", "Storage area network"],
  ["sase", "Secure Access Service Edge"],
  ["sd-wan", "Software-defined wide area network"],
  ["sdn", "Software-defined networking"],
  ["sfp", "Small form-factor pluggable"],
  ["sla", "Service level agreement"],
  ["slaac", "Stateless Address Autoconfiguration"],
  ["smb", "Server Message Block"],
  ["snmp", "Simple Network Management Protocol"],
  ["snr", "Signal-to-noise ratio"],
  ["sse", "Secure Service Edge"],
  ["ssh", "Secure Shell"],
  ["ssid", "Service set identifier"],
  ["stp", "Spanning Tree Protocol"],
  ["svi", "Switch virtual interface"],
  ["tcp", "Transmission Control Protocol"],
  ["tls", "Transport Layer Security"],
  ["traceroute / tracert", "traceroute / trace route (tracert)"],
  ["udp", "User Datagram Protocol"],
  ["ups", "Uninterruptible power supply"],
  ["vdi", "Virtual desktop infrastructure"],
  ["vlan", "Virtual local area network"],
  ["vpc", "Virtual private cloud"],
  ["vpn concentrator", "Virtual private network concentrator"],
  ["wan", "Wide area network"],
  ["wpa3", "Wi-Fi Protected Access 3"],
]);

const phraseExpansions = [
  ["802.1Q", "IEEE 802.1Q"],
  ["802.1X", "IEEE 802.1X"],
  ["ACL", "access control list (ACL)"],
  ["AP", "access point (AP)"],
  ["APIPA", "Automatic Private IP Addressing (APIPA)"],
  ["ARP", "Address Resolution Protocol (ARP)"],
  ["BSSID", "basic service set identifier (BSSID)"],
  ["CIDR", "Classless Inter-Domain Routing (CIDR)"],
  ["CRC", "cyclic redundancy check (CRC)"],
  ["DDoS", "distributed denial of service (DDoS)"],
  ["DHCP", "Dynamic Host Configuration Protocol (DHCP)"],
  ["DNS", "Domain Name System (DNS)"],
  ["DoS", "denial of service (DoS)"],
  ["EMI", "electromagnetic interference (EMI)"],
  ["EOL", "end of life (EOL)"],
  ["EOS", "end of support (EOS)"],
  ["FTP", "File Transfer Protocol (FTP)"],
  ["HTTP", "Hypertext Transfer Protocol (HTTP)"],
  ["HTTPS", "Hypertext Transfer Protocol Secure (HTTPS)"],
  ["IDS", "intrusion detection system (IDS)"],
  ["IPS", "intrusion prevention system (IPS)"],
  ["IPAM", "IP address management (IPAM)"],
  ["IPsec", "Internet Protocol Security (IPsec)"],
  ["IPv4", "Internet Protocol version 4 (IPv4)"],
  ["IPv6", "Internet Protocol version 6 (IPv6)"],
  ["MAC", "media access control (MAC)"],
  ["MFA", "multi-factor authentication (MFA)"],
  ["MTBF", "mean time between failures (MTBF)"],
  ["MTTR", "mean time to repair (MTTR)"],
  ["NAC", "network access control (NAC)"],
  ["NAS", "network-attached storage (NAS)"],
  ["NAT", "network address translation (NAT)"],
  ["NDP", "Neighbor Discovery Protocol (NDP)"],
  ["NTP", "Network Time Protocol (NTP)"],
  ["OTDR", "optical time-domain reflectometer (OTDR)"],
  ["PAT", "port address translation (PAT)"],
  ["PDU", "power distribution unit (PDU)"],
  ["PoE", "Power over Ethernet (PoE)"],
  ["QoS", "Quality of Service (QoS)"],
  ["RADIUS", "Remote Authentication Dial-In User Service (RADIUS)"],
  ["RBAC", "role-based access control (RBAC)"],
  ["RDP", "Remote Desktop Protocol (RDP)"],
  ["RPO", "recovery point objective (RPO)"],
  ["RSSI", "received signal strength indicator (RSSI)"],
  ["RTO", "recovery time objective (RTO)"],
  ["SAN", "storage area network (SAN)"],
  ["SASE", "Secure Access Service Edge (SASE)"],
  ["SD-WAN", "software-defined wide area network (SD-WAN)"],
  ["SDN", "software-defined networking (SDN)"],
  ["SFP", "small form-factor pluggable (SFP)"],
  ["SLAAC", "Stateless Address Autoconfiguration (SLAAC)"],
  ["SLA", "service level agreement (SLA)"],
  ["SMB", "Server Message Block (SMB)"],
  ["SNMP", "Simple Network Management Protocol (SNMP)"],
  ["SNR", "signal-to-noise ratio (SNR)"],
  ["SSE", "Secure Service Edge (SSE)"],
  ["SSH", "Secure Shell (SSH)"],
  ["SSID", "service set identifier (SSID)"],
  ["STP", "Spanning Tree Protocol (STP)"],
  ["SVI", "switch virtual interface (SVI)"],
  ["TCP", "Transmission Control Protocol (TCP)"],
  ["TLS", "Transport Layer Security (TLS)"],
  ["UDP", "User Datagram Protocol (UDP)"],
  ["UPS", "uninterruptible power supply (UPS)"],
  ["VDI", "virtual desktop infrastructure (VDI)"],
  ["VLAN", "virtual local area network (VLAN)"],
  ["VPC", "virtual private cloud (VPC)"],
  ["VPN", "virtual private network (VPN)"],
  ["WAN", "wide area network (WAN)"],
  ["WPA3", "Wi-Fi Protected Access 3 (WPA3)"],
  ["ip", "Internet Protocol (IP)"],
].sort((a, b) => b[0].length - a[0].length);

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function getFlashcardRevealTerm(front) {
  const term = String(front ?? "").trim();
  const exact = exactRevealTerms.get(term.toLowerCase());
  if (exact) return exact;

  return phraseExpansions.reduce((current, [abbreviation, expansion]) => {
    const pattern = new RegExp(`(^|[^A-Za-z0-9])${escapeRegex(abbreviation)}(?=$|[^A-Za-z0-9])`, "g");
    return current.replace(pattern, (_, prefix) => `${prefix}${expansion}`);
  }, term);
}
